// Code generated by protoc-gen-go-warrior. DO NOT EDIT.
// versions:
// - protoc-gen-go-warrior v0.0.1
// source: api/metadata/metadata.proto

package metadata

import (
	context "context"
	application "github.com/go-warrior/pkg/application"
)

// IMetadataUseCase is the server API for Metadata service.
// for forward compatibility
type IMetadataUseCase interface {
	ListServices(context.Context, *ListServicesRequest) (*ListServicesReply, error)
	GetServiceDesc(context.Context, *GetServiceDescRequest) (*GetServiceDescReply, error)
}

// @di di文件根据注解自动生成
func RegisterMetadataServer(app application.Application, srv IMetadataUseCase) {
	if app.HttpServer() != nil {
		RegisterMetadataHTTPServer(app.HttpServer(), srv)
	}
	if app.GrpcServer() != nil {
		RegisterMetadataGrpcServer(app.GrpcServer(), srv)
	}
}
